-- Dunnworks: Bordon campaign, 50 previews and 50 reports
-- Generated 16 September 2026. Run in the SQL editor of project acdpgarasgfhvupzsbxf,
-- after dunnworks-schema.sql and dunnworks-keys.sql.
--
-- Two inserts. The first registers the 100 locked pages so a passphrase can be
-- reissued from the admin without rebuilding the file. No wrap yet, so the
-- passphrase each page was built with keeps working until the first reissue.
-- The second registers the 50 projects. published is false on purpose: these are
-- cold prospects, and their concepts must not be listed on the public previews page.

begin;

insert into public.dw_project_keys (slug, doc, file_salt, file_iter) values
  ('1st-advanced-landscapes', 'site', 'zJkfLFJuOzpcgzT9i+Fm8w==', 600000),
  ('1st-advanced-landscapes', 'report', 'kb/ocbCivQCDmcoI5fXJCw==', 600000),
  ('alton-vehicle-hire', 'site', 'hlPT7opfXIsLf3eUSSOPpw==', 600000),
  ('alton-vehicle-hire', 'report', 'XTrljGo0DRDC/wD0cYuQ+Q==', 600000),
  ('arnolds-garage', 'site', 'Im3u62R91qJ9QZT1dW0NLQ==', 600000),
  ('arnolds-garage', 'report', 'wn2uYrBIep4ldnjbVj0RTA==', 600000),
  ('bentley-beavoir', 'site', '2P+Sa67QjrisfhrVorhh+A==', 600000),
  ('bentley-beavoir', 'report', 'y6ZOVuXxNnnSUvvNdkXoew==', 600000),
  ('browns-of-alton', 'site', 'cshzu+0lkShK8vlw3UI26Q==', 600000),
  ('browns-of-alton', 'report', 'bgUPKL2QA3QaiyVCPU5Fow==', 600000),
  ('country-market', 'site', '8nHjt5w6AFTOiVJjc6ArmQ==', 600000),
  ('country-market', 'report', 'q7y0DOW8kvFpy4vAvkP9Ow==', 600000),
  ('flower-vogue', 'site', 'FSPucdKw19GiD4gkD2Xxqw==', 600000),
  ('flower-vogue', 'report', 'svzuPjZYLQSATRwzQ6gKQg==', 600000),
  ('gn-groundworks', 'site', 'jIp669R+WbEONmBe2MpNXQ==', 600000),
  ('gn-groundworks', 'report', 'zyF9OnvJ6/QpMcjgUsMUbg==', 600000),
  ('gentle-dental-care', 'site', '/aBfyzEX/iBQplchfMROiQ==', 600000),
  ('gentle-dental-care', 'report', 'FqD+1loSmJLQeIomnUIRwA==', 600000),
  ('gillett-holden', 'site', 'VCFa4Jx4+TOtrW7y+3xoPQ==', 600000),
  ('gillett-holden', 'report', 'Ccb3IyJiq5Qrt9I7Nw2J5g==', 600000),
  ('handford-construction', 'site', 'a29pp7r11h/nhvtZVTUjYQ==', 600000),
  ('handford-construction', 'report', 'cjiTRt+3Us7UGDl/APxcCw==', 600000),
  ('haslemere-fencing', 'site', 'XKqm5JkJX8mEsI0E5ZeF6A==', 600000),
  ('haslemere-fencing', 'report', 'UHcRBIfPkwCleP3zjZVj4Q==', 600000),
  ('j-gatcum-landscaping', 'site', 'ZRstJags9BGSzIZT9YmtRA==', 600000),
  ('j-gatcum-landscaping', 'report', '/6s3/6TB1i1CRF9AnPL9Qg==', 600000),
  ('john-hughes-fencing-and-land', 'site', '5ImIe87uYuVya2reQZVkzA==', 600000),
  ('john-hughes-fencing-and-land', 'report', 'crNv2RWJ7oA67XgqU/hG6g==', 600000),
  ('kingsley-tree-care-and-lands', 'site', 'lx+DYTbqNyq26h/QCBNBig==', 600000),
  ('kingsley-tree-care-and-lands', 'report', '4nkA+Xajz11msbUEZ5v+Aw==', 600000),
  ('liss-garage-services', 'site', 'm2Fzqdw0EEURzLDZJXgrvA==', 600000),
  ('liss-garage-services', 'report', 'zey6kcGap2UDYw7pXGnbwQ==', 600000),
  ('mike-frost-carpets', 'site', '2OpsRmlLehcy76hps11MZQ==', 600000),
  ('mike-frost-carpets', 'report', 'nOfhPBiuQAtymPtksrDJxw==', 600000),
  ('reeds-hair-and-beauty', 'site', 'pcsxpA+ocmG+BNuQBDs75g==', 600000),
  ('reeds-hair-and-beauty', 'report', 'H3j6stzODp+0f1322CPG7Q==', 600000),
  ('rozario-projects', 'site', 'dg76+5unJxcdfc0dmzIjPg==', 600000),
  ('rozario-projects', 'report', 'W5nVjT5jL98yq+ZL7nO+Rw==', 600000),
  ('the-flying-bull', 'site', '6rPyZGPyfpLIVr2htM5lLg==', 600000),
  ('the-flying-bull', 'report', '9AYedr5BuZT/dUht6loFBg==', 600000),
  ('total-profiles', 'site', 'xEB2Cwapio2txYbdNaJtRA==', 600000),
  ('total-profiles', 'report', '4AtaFhGVNLDHvsfAKI0YCQ==', 600000),
  ('upper-neatham-mill-farm', 'site', 'CLAjFO/hwWY4OBLC3/pGUA==', 600000),
  ('upper-neatham-mill-farm', 'report', 'MAjICorOctfXRLAAmuBi+Q==', 600000),
  ('williams-of-bordon', 'site', 'qTbkmks3bzrigtk1nva5zA==', 600000),
  ('williams-of-bordon', 'report', 'hcXwcwZjJR3cT1plZv3Uhg==', 600000),
  ('alton-station-storage', 'site', 'F7DUKY7e6D/pY2hpIsMUZA==', 600000),
  ('alton-station-storage', 'report', 'qfqu+n6L5P78V8ngxFKBIQ==', 600000),
  ('ampella-maintenance', 'site', 'S1p0UZ1azSvcLE62FnqqGA==', 600000),
  ('ampella-maintenance', 'report', 'rE4vlH3XSbG0OYwQdHeMvQ==', 600000),
  ('andrew-james-driveways', 'site', 'RiHZsgU3PtjpLoOwNxv3Mg==', 600000),
  ('andrew-james-driveways', 'report', 'nUeNysBHR8U8PfUnYOIENw==', 600000),
  ('bte-automotive', 'site', 'v8xxDrOvFaX0GOcV23JBPA==', 600000),
  ('bte-automotive', 'report', 'rUw3WW6QihBW5LIzgDu5mg==', 600000),
  ('drb-contractors', 'site', 'Nm9BxLyUrwCNHP+7U9zkhQ==', 600000),
  ('drb-contractors', 'report', 'kA9o5ZKgEBSXLY+LOcMj9g==', 600000),
  ('downie-gadban', 'site', 'pO3LBYYIFM2767qjtu3OSg==', 600000),
  ('downie-gadban', 'report', 'gXPxp8N9aeemsxZN2U9L2w==', 600000),
  ('ecs-plumbing-and-heating', 'site', 'xRGLvazCy+bYcCZQKITT2g==', 600000),
  ('ecs-plumbing-and-heating', 'report', 'eUJR/cJOfoZrbXTSNjUpMQ==', 600000),
  ('hampshire-lettings-company', 'site', 'FuIqnH8G63YvvShTd+GldQ==', 600000),
  ('hampshire-lettings-company', 'report', '9ZV5t6iN52fciKKon8Tezw==', 600000),
  ('hanson-s-hair', 'site', 'fGB62Sg4UZVvEKLvtyQoBQ==', 600000),
  ('hanson-s-hair', 'report', '4wowOHR7KE4iS4pAmrhnAA==', 600000),
  ('ideal-for-bathrooms', 'site', 'WoKjvpLTt9hUt+l7YI8Kxw==', 600000),
  ('ideal-for-bathrooms', 'report', 'PsEMajfTts0rQmuAV8Lr+g==', 600000),
  ('jrs-plumbing-and-heating', 'site', 'BX4MuaOlcfr5ZaKXK2MhFw==', 600000),
  ('jrs-plumbing-and-heating', 'report', 'dwPHL4kV9oAhWI/QsbUFoA==', 600000),
  ('kingswood-property-services', 'site', 'Trvk00afJdyWldiY+4gwng==', 600000),
  ('kingswood-property-services', 'report', 'MJPUSwvE/RIHCx6NPADO0A==', 600000),
  ('liphook-skin-beauty', 'site', '2hOzvPoIVCH1Y8SYF4d6zQ==', 600000),
  ('liphook-skin-beauty', 'report', 'Voy3QICXeWgYAghMydKojQ==', 600000),
  ('liphook-tree-surgeons', 'site', 'TKK18QvR/QxP7lWqEk/lvg==', 600000),
  ('liphook-tree-surgeons', 'report', 'M+rtZH8jJFNrXoC81v8Pcg==', 600000),
  ('lodge-automotive', 'site', 'Uua+ems+cfPGtM1yL5LGjQ==', 600000),
  ('lodge-automotive', 'report', 'YPBKIYNmRN0qjF71/vMWUA==', 600000),
  ('luff-s-farm-shop', 'site', 'MiaXA7kMIfX9/9ba7V7Bcg==', 600000),
  ('luff-s-farm-shop', 'report', 'WbQL/xxjc3hnRDKEvXkUWg==', 600000),
  ('mainline-scaffolding', 'site', 'go92gbvExwyDnedBf6RfnA==', 600000),
  ('mainline-scaffolding', 'report', 'XjYzJq+KJnt6ar2GJ3XUkg==', 600000),
  ('messenger-and-sons', 'site', 'WykRfc3hcQ5/v82MPJf5eA==', 600000),
  ('messenger-and-sons', 'report', 'e5dcCKhjK8uaw/a9r1tJJQ==', 600000),
  ('osgoods', 'site', 'Dksms0xzGHpyR9D70qKl3A==', 600000),
  ('osgoods', 'report', 'hEtAwANfTX3q32LbuW45CQ==', 600000),
  ('selborne-arms', 'site', '/544Kvktafp3Tk+4TvGBjg==', 600000),
  ('selborne-arms', 'report', 'E4pUAGGtPhvfT5aNTpGwzg==', 600000),
  ('the-deers-hut', 'site', 'GVQySt4AwJ5jQYiciDMvMw==', 600000),
  ('the-deers-hut', 'report', 'hYMiZrt2n8Fu3y+XOngCpw==', 600000),
  ('the-holly-bush', 'site', 'PIICPJCrot3Mw1+XZrIzEQ==', 600000),
  ('the-holly-bush', 'report', 'vG+uqYzb/lT6/U420N2/1A==', 600000),
  ('thursley-tree-and-garden-ser', 'site', '5n0MOXQABoqAaGskRyZiLQ==', 600000),
  ('thursley-tree-and-garden-ser', 'report', 'wdHUcIUYwlY24830esm+Ug==', 600000),
  ('velophysio', 'site', 'GXysBa1S1R0ilN0EYqj8bw==', 600000),
  ('velophysio', 'report', 'RUodIQ8sOlNExZ3zKdrxsg==', 600000),
  ('bellemoor-removals-and-stora', 'site', '1Qk6s8J+vcyyXaGlXJm4Ew==', 600000),
  ('bellemoor-removals-and-stora', 'report', 'Aim8yM2kAAtC6fa0bW801g==', 600000),
  ('bizcon-grayshott', 'site', 'R/OKPjBif9n4mKZUpg1A+Q==', 600000),
  ('bizcon-grayshott', 'report', 'YhJ+63Hk+hgG4L49cXH0Bw==', 600000),
  ('greysmere-associates', 'site', 'B275xtsWuIgPZ8YOfS3m6w==', 600000),
  ('greysmere-associates', 'report', 'yxX10GR530CMnm886xGN8w==', 600000)
on conflict (slug, doc) do update set
  file_salt = excluded.file_salt,
  file_iter = excluded.file_iter;

insert into public.dw_projects
  (slug, name, sector, blurb, kind, status, is_live, has_preview, has_report, pages, sort_order, published)
values
  ('1st-advanced-landscapes', '1st Advanced Landscapes', 'Driveways and landscaping', 'Hindhead. Driveways and landscaping. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 200, false),
  ('alton-vehicle-hire', 'Alton Vehicle Hire', 'Vehicle hire', 'Four Marks. Vehicle hire. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 201, false),
  ('arnolds-garage', 'Arnolds Garage', 'Motor trade', 'Haslemere. Motor trade. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 202, false),
  ('bentley-beavoir', 'Bentley Beavoir', 'Building and project management', 'Ropley. Building and project management. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 203, false),
  ('browns-of-alton', 'Browns of Alton', 'Flooring', 'Alton. Flooring. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 204, false),
  ('country-market', 'Country Market', 'Retail and hospitality', 'Kingsley. Retail and hospitality. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 205, false),
  ('flower-vogue', 'Flower Vogue', 'Florist', 'Grayshott. Florist. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 206, false),
  ('gn-groundworks', 'GN Groundworks', 'Groundworks', 'Bordon. Groundworks. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 207, false),
  ('gentle-dental-care', 'Gentle Dental Care', 'Health', 'Alton. Health. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 208, false),
  ('gillett-holden', 'Gillett & Holden', 'Appliance sales and repair', 'Hindhead. Appliance sales and repair. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 209, false),
  ('handford-construction', 'Handford Construction', 'Building', 'Lindford. Building. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 210, false),
  ('haslemere-fencing', 'Haslemere Fencing', 'Fencing', 'Haslemere. Fencing. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 211, false),
  ('j-gatcum-landscaping', 'J. Gatcum Landscaping', 'Landscaping', 'Headley Down. Landscaping. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 212, false),
  ('john-hughes-fencing-and-land', 'John Hughes Fencing and Landscapes', 'Fencing and landscaping', 'Bordon. Fencing and landscaping. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 213, false),
  ('kingsley-tree-care-and-lands', 'Kingsley Tree Care and Landscaping', 'Tree surgery and landscaping', 'Kingsley. Tree surgery and landscaping. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 214, false),
  ('liss-garage-services', 'Liss Garage Services', 'Motor trade', 'Liss. Motor trade. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 215, false),
  ('mike-frost-carpets', 'Mike Frost Carpets', 'Flooring', 'Alton. Flooring. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 216, false),
  ('reeds-hair-and-beauty', 'Reeds Hair and Beauty', 'Hair and beauty', 'Liphook. Hair and beauty. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 217, false),
  ('rozario-projects', 'Rozario Projects', 'Building and joinery', 'Greatham. Building and joinery. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 218, false),
  ('the-flying-bull', 'The Flying Bull', 'Hospitality', 'Liss. Hospitality. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 219, false),
  ('total-profiles', 'Total Profiles', 'Windows and glazing', 'Bordon. Windows and glazing. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 220, false),
  ('upper-neatham-mill-farm', 'Upper Neatham Mill Farm', 'Hospitality', 'Holybourne. Hospitality. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 221, false),
  ('williams-of-bordon', 'Williams of Bordon', 'Plant hire and demolition', 'Whitehill. Plant hire and demolition. Cold proposal, critical band.', 'preview', 'build', false, true, true, 2, 222, false),
  ('alton-station-storage', 'Alton Station Storage', 'Self storage', 'Alton. Self storage. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 223, false),
  ('ampella-maintenance', 'Ampella Maintenance', 'Heating and plumbing', 'Grayshott. Heating and plumbing. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 224, false),
  ('andrew-james-driveways', 'Andrew James Driveways', 'Driveways and landscaping', 'Haslemere. Driveways and landscaping. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 225, false),
  ('bte-automotive', 'BTE Automotive', 'Motor trade', 'Bordon. Motor trade. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 226, false),
  ('drb-contractors', 'DRB Contractors', 'Fencing and plant hire', 'Liss Forest. Fencing and plant hire. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 227, false),
  ('downie-gadban', 'Downie & Gadban', 'Legal', 'Alton. Legal. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 228, false),
  ('ecs-plumbing-and-heating', 'ECS Plumbing and Heating', 'Plumbing and heating', 'Four Marks. Plumbing and heating. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 229, false),
  ('hampshire-lettings-company', 'Hampshire Lettings Company', 'Lettings', 'Alton. Lettings. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 230, false),
  ('hanson-s-hair', 'Hanson''s Hair', 'Hair and beauty', 'Liphook. Hair and beauty. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 231, false),
  ('ideal-for-bathrooms', 'Ideal For Bathrooms', 'Kitchens and bathrooms', 'Alton. Kitchens and bathrooms. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 232, false),
  ('jrs-plumbing-and-heating', 'JRS Plumbing and Heating', 'Plumbing and heating', 'Alton. Plumbing and heating. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 233, false),
  ('kingswood-property-services', 'Kingswood Property Services', 'Estate agency', 'Bordon. Estate agency. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 234, false),
  ('liphook-skin-beauty', 'Liphook Skin & Beauty', 'Hair and beauty', 'Liphook. Hair and beauty. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 235, false),
  ('liphook-tree-surgeons', 'Liphook Tree Surgeons', 'Tree surgery', 'Liphook. Tree surgery. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 236, false),
  ('lodge-automotive', 'Lodge Automotive', 'Motor trade', 'Liphook. Motor trade. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 237, false),
  ('luff-s-farm-shop', 'Luff''s Farm Shop', 'Retail', 'Headley. Retail. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 238, false),
  ('mainline-scaffolding', 'Mainline Scaffolding', 'Scaffolding', 'Liss. Scaffolding. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 239, false),
  ('messenger-and-sons', 'Messenger and Sons', 'Building', 'Four Marks. Building. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 240, false),
  ('osgoods', 'Osgoods', 'Motor trade', 'Alton. Motor trade. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 241, false),
  ('selborne-arms', 'Selborne Arms', 'Hospitality', 'Selborne. Hospitality. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 242, false),
  ('the-deers-hut', 'The Deers Hut', 'Hospitality', 'Liphook. Hospitality. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 243, false),
  ('the-holly-bush', 'The Holly Bush', 'Hospitality', 'Headley. Hospitality. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 244, false),
  ('thursley-tree-and-garden-ser', 'Thursley Tree and Garden Services', 'Tree surgery', 'Thursley. Tree surgery. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 245, false),
  ('velophysio', 'Velophysio', 'Health', 'Liss. Health. Cold proposal, poor band.', 'preview', 'build', false, true, true, 2, 246, false),
  ('bellemoor-removals-and-stora', 'Bellemoor Removals and Storage', 'Removals and storage', 'Shalden. Removals and storage. Cold proposal, dated band.', 'preview', 'build', false, true, true, 2, 247, false),
  ('bizcon-grayshott', 'Bizcon Grayshott', 'Signage and print', 'Grayshott. Signage and print. Cold proposal, dated band.', 'preview', 'build', false, true, true, 2, 248, false),
  ('greysmere-associates', 'Greysmere Associates', 'Financial advice', 'Hindhead. Financial advice. Cold proposal, dated band.', 'preview', 'build', false, true, true, 2, 249, false)
on conflict (slug) do update set
  name        = excluded.name,
  sector      = excluded.sector,
  blurb       = excluded.blurb,
  has_report  = excluded.has_report,
  pages       = excluded.pages,
  sort_order  = excluded.sort_order;

commit;

-- Check: expect 100 and 50.
-- select count(*) from public.dw_project_keys where slug in (select slug from public.dw_projects where sort_order >= 200);
-- select count(*) from public.dw_projects where sort_order >= 200;
